### ISSUE TITLE
👍

### ISSUE THREAD

**Issue by darkrain88** [xzhih/nginx-compile#1]
能帮我配置X250的黑苹果吗？ 声音搞不出来

**Comment by xzhih** [comment]
艹，黑苹果来这里问。。。声音的话，用appleALC，加上音频节点就行了。

只要知道声卡型号，然后在appleALC的项目页面查找音频节点，使用fb-patcher注入就行

**Comment by darkrain88** [comment]
@xzhih 哈哈找不到节点奇怪

**Comment by xzhih** [comment]
https://github.com/acidanthera/AppleALC/wiki/Supported-codecs
